### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by uptownhr**
Added Dockerfile and docker-compose.yml.

### CODE REVIEW

**Comment by baclap** [comment]
-28,412 is awesome, haha

great improvements, thanks!

**Comment by uptownhr** [comment]
No problem.

What is "-28,412" referring too? Sorry, can't seem to find it.

**Comment by baclap** [comment]
The red/green numbers show how many lines of code got removed/added. Because your pull request deleted node_modules from the repo it said you removed over 28,000 LOC, which is abnormally large of course.

**Comment by uptownhr** [comment]
oooo. Thought you were referring to a line of code some where :)

**Pull request merged**
